# -*- coding: utf-8 -*-
"""web-scrap-maktabah-shamela.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vioFdachT-6RXB50dXB7X3KEjs-LUc3W
"""

# Scrap contents from maktabah shamela
import requests
from bs4 import BeautifulSoup

# gunakan fungsi ini untuk scrap 1 halaman
# id_buku bisa dilihat dari URL 
def request_page(id_buku, nomor_halaman):
    URL = "https://shamela.ws/book/"+str(id_buku)+"/"+str(nomor_halaman)
    page = requests.get(URL)

    soup = BeautifulSoup(page.content, "html.parser")
    results = soup.find(id="wrapper")
    job_elements = results.find_all("div", class_="nass")
    
    content_in = ""
    for job_element in job_elements:
        for the_element in job_element.find_all("p"):
            content_in += the_element.text+'\n'
    
    return content_in

# gunakan fungsi ini untuk scrap 1 buku
def get_book(id_buku, nomor_halaman_awal, nomor_halaman_akhir, save_to_file=False):
    content = ""

    for i in range(nomor_halaman_awal, nomor_halaman_akhir):
        content += request_page(id_buku, i)
    
    if save_to_file :
        file = open("result.txt", "w")
        file.write(content)
        file.close
    else:
        print(content)

# contoh penggunaan
# 12836: contoh id buku Arbain Nawawi
get_book(12836, 1, 3)

# contoh untuk save hasil kedalam file
#get_book(12836, 1, 3, True)